services:
  backend:
    image: ghcr.io/muratselcuk/nodejs-nextjs-blog-backend:stage
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app         # KODLARI container’a bağlıyoruz
      - backend-data:/app/data # SQLITE VERİLERİ ayrı volume’da
    env_file:
      - ./backend/.env.docker
    environment:
      - NODE_ENV=development


  frontend:
    image: ghcr.io/muratselcuk/nodejs-nextjs-blog-frontend:stage
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env.local
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:3001
      - API_BASE_URL=http://backend:3001
    volumes:
      - ./frontend:/app

volumes:
  backend-data: