services:
  backend:
    image: ghcr.io/muratselcuk/nodejs-nextjs-blog-backend:prod
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env.docker
    environment:
      - NODE_ENV=production
    volumes:
      - ./data:/app/data

  frontend:
    image: ghcr.io/muratselcuk/nodejs-nextjs-blog-frontend:prod
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=https://www.muratselcuk.com/api
      - API_BASE_URL=http://backend:3001
