# Temel imaj
FROM node:18

# Çalışma dizinini oluştur
WORKDIR /app

# package.json ve package-lock.json'u kopyala
COPY package*.json ./

# Bağımlılıkları kur
RUN npm install --production

# Uygulama dosyalarını kopyala
COPY . .

# API portunu aç
EXPOSE 3000

# Başlangıç komutu
CMD ["npm", "start"]
