name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # v1.0.0 gibi prod release'leri tetikler

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      ##### 👉 ENV dosyası oluştur (her iki ortam için)
      - name: Create backend .env.docker file
        run: |
          echo "SQLITE_PATH=/app/data/blog.sqlite" >> backend/.env.docker
          echo "PORT=3001" >> backend/.env.docker

      #### 👉 BACKEND STAGE
      - name: Build backend:stage image
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -f backend/Dockerfile.stage -t ghcr.io/${{ github.repository }}-backend:stage ./backend

      - name: Push backend:stage image
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ghcr.io/${{ github.repository }}-backend:stage

      #### 👉 BACKEND PROD
      - name: Build backend:prod image
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker buildx build \
            --platform linux/arm/v7 \
            -f backend/Dockerfile \
            -t ghcr.io/${{ github.repository }}-backend:prod \
            --push \
            ./backend


      #### 👉 FRONTEND STAGE
      - name: Build frontend:stage image
        if: github.ref == 'refs/heads/main'
        run: |
          docker build \
            -f frontend/Dockerfile.stage \
            --build-arg API_BASE_URL=http://backend:3001 \
            --build-arg NEXT_PUBLIC_API_BASE_URL=http://ThinkPadE14:3001 \
            -t ghcr.io/${{ github.repository }}-frontend:stage ./frontend

      - name: Push frontend:stage image
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ghcr.io/${{ github.repository }}-frontend:stage

      #### 👉 FRONTEND PROD
      - name: Build frontend:prod image
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker buildx build \
            --platform linux/arm/v7 \
            -f frontend/Dockerfile \
            --build-arg API_BASE_URL=http://backend:3001 \
            --build-arg NEXT_PUBLIC_API_BASE_URL=https://www.muratselcuk.com \
            -t ghcr.io/${{ github.repository }}-frontend:prod \
            --push \
            ./frontend

